persistence:
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort
  reclaimPolicy: Retain
  migratable: "true"

defaultSettings:
  replicaAutoBalance: least-effort
  defaultLonghornStaticStorageClass: longhorn
  recurringJobMaxRetention: 30
  nodeDrainPolicy: allow-if-replica-is-stopped
  concurrentReplicaRebuildPerNodeLimit: "3"
  concurrentAutomaticEngineUpgradePerNodeLimit: "3"
  removeSnapshotsDuringFilesystemTrim: "true"

longhornUI:
  replicas: 2