persistence:
  defaultClassReplicaCount: 3
  defaultDataLocality: best-effort
  reclaimPolicy: Retain
  migratable: "true"

defaultSettings:
  replicaAutoBalance: best-effort
  concurrentReplicaRebuildPerNodeLimit: "3"
  concurrentAutomaticEngineUpgradePerNodeLimit: "3"
  removeSnapshotsDuringFilesystemTrim: "true"

longhornUI:
  replicas: 2