persistence:
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort
  reclaimPolicy: Retain
  migratable: "true"

defaultSettings:
  replicaAutoBalance: best-effort
  concurrentAutomaticEngineUpgradePerNodeLimit: "3"

longhornUI:
  replicas: 2