---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mealie
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mealie.mandariini.uk`)
      kind: Rule
      services:
        - name: mealie
          namespace: mealie
          port: 9000
      middlewares:
        - name: default-headers
          namespace: default
  tls:
    secretName: mandariini-uk-tls