---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bentopdf
  name: bentopdf
  namespace: bentopdf
spec:
  selector:
    app: bentopdf
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080