---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ville
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
    - websecxt
  routes:
    - match: Host(`paukkunen.de`)
      kind: Rule
      services:
        - name: nginx-ville
          namespace: nginx-ville
          port: 80
      middlewares:
        - name: default-headers
          namespace: default
    - match: Host(`www.paukkunen.de`)
      kind: Rule
      services:
        - name: nginx-ville
          namespace: nginx-ville
          port: 80
      middlewares:
        - name: default-headers
          namespace: default
        - name: redirect-to-non-www
          namespace: nginx-ville
  tls:
    secretName: paukkunen-de-tls