autoscaling:
  enabled: true
  minReplicas: "1"
  maxReplicas: "5"
  targetCPUUtilizationPercentage: "70"
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
containerSecurityContext:
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
extraVolumes:
  - name: html
    persistentVolumeClaim:
      claimName: nginx-ville
extraVolumeMounts:
  - name: html
    mountPath: /usr/share/nginx/html