services:
  duplicati:
    container_name: duplicati
    image: lscr.io/linuxserver/duplicati:v2.2.0.1_stable_2025-11-09-ls268
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
      - CLI_ARGS= #optional
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI__WEBSERVICE_PASSWORD}
    env_file:
      - .env
    volumes:
      - /opt/duplicati/config:/config
      - /mnt/nfs/backup:/backups
      - /opt:/docker
      - /etc/samba:/samba
      - /home/smb/acer-server:/samba-data
      - /srv/nfs:/kubernetes
#    ports:
#      - 8200:8200
    restart: unless-stopped
    networks:
      - traefik_default
    labels:
#      - com.centurylinklabs.watchtower.monitor-only=false
      - traefik.enable=true
      - traefik.http.routers.duplicati.rule=Host(`duplicati.m73-1.mandariini.uk`)
      - traefik.http.routers.duplicati.entrypoints=websecure
      - traefik.http.routers.duplicati.tls=true
      - traefik.http.services.duplicati.loadbalancer.server.port=8200
#      - traefik.http.routers.duplicati.middlewares=authentik@file
      - traefik.docker.network=traefik_default

networks:
  traefik_default:
    external: true
