nextcloud:
  host: cloud.mandariini.uk
  existingSecret:
    enabled: true
    secretName: envsecrets
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
    smtpUsernameKey: smtp-username
    smtpPasswordKey: smtp-password
    smtpHostKey: smtp-host
  trustedDomains: cloud.mandariini.uk
  mail:
    enabled: true
    fromAddress: cloud
    domain: mandariini.uk
    smtp:
      secure: ""
      port: 587
      authtype: LOGIN
  podSecurityContext:
    fsGroupChangePolicy: "OnRootMismatch"

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true

  existingSecret:
    enabled: true
    secretName: envsecrets
    usernameKey: mariadb-username
    passwordKey: mariadb-password

mariadb:
  enabled: true
  auth:
    existingSecret: envsecrets
  primary:
    persistence:
      enabled: true
      existingClaim: db

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      existingClaim: redis
  replica:
    persistence:
      enabled: false

cronjob:
  enabled: true

persistence:
  enabled: true
  existingClaim: config

  nextcloudData:
    enabled: true
    existingClaim: data