---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jenkins.mandariini.uk`)
      kind: Rule
      services:
        - name: jenkins
          namespace: jenkins
          port: 8080
      middlewares:
        - name: default-headers
          namespace: default
  tls:
    secretName: mandariini-uk-tls