---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: media
spec:
  selector:
    app: jellyfin
  ports:
    - name: web
      port: 8096
      protocol: TCP
      targetPort: 8096
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin-discovery
  namespace: media
spec:
  selector:
    app: jellyfin
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.10.50
  ports:
    - name: client
      port: 7359
      protocol: UDP
      targetPort: 7359
    - name: service
      port: 1900
      protocol: UDP
      targetPort: 1900
  type: LoadBalancer