apiVersion: v1
kind: ConfigMap
metadata:
  name: limiter-toml
  namespace: searxng
data:
  limiter.toml: |
    [botdetection]
    
    trusted_proxies = [
      '127.0.0.0/8',
      '::1',
      # '192.168.0.0/16',
      # '172.16.0.0/12',
      '10.0.0.0/8',
      # 'fd00::/8',
    ]